name: Docker Image CI

on:
  push:
    branches:
      - "master"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Qemu
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:dockerfile"
        file: ./Dockerfile
        push: true
        plataforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
        tags: ${{ secrets.DOCKER_USERNAME }}/kms-server:latest,${{ secrets.DOCKER_USERNAME }}/kms-server:${{ steps.date.outputs.date }}