name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
         cd dockerfile
         docker build . --file Dockerfile --tag linux8a/kms-server:$(date +%s)
         docker push linux8a/kms-server:$(date +%s)
