name: Docker Image CI Schedule

on:
  schedule:
    - cron:  '0 2 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - uses: actions/checkout@v3
    - name: Check if update available
      id: check
      uses: lucacome/docker-image-update-checker@v1
      with:
        base-image: alpine:latest
        image: linux8a/kms-server:latest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: steps.check.outputs.needs-updating == 'true'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:dockerfile"
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kms-server:latest , ${{ secrets.DOCKER_USERNAME }}/kms-server:${{ steps.date.outputs.date }}
      if: steps.check.outputs.needs-updating == 'true'
